---
- name: Local install
  hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install htop
    apt:
      name: htop
      state: present

  - name: Install tmux
    apt:
      name: tmux
      state: present

  - name: Add key for Zentyal 7.1
    ansible.builtin.get_url:
      url: http://keys.zentyal.org/zentyal-7.1-packages-org.asc
      dest: /etc/apt/trusted.gpg.d/zentyal.asc
      mode: '0644'
      force: true

  - name: Add repo for Zentyal 7.1
    ansible.builtin.apt_repository:
      repo: deb http://packages.zentyal.org/zentyal 7.1 main extra
      state: present

  - name: Installing Zentyal 7.1
    apt:
      name: 
        - zentyal
      state: latest
      force_apt_get: true
      update_cache: true
